### ISSUE TITLE
Uncaught (in promise): TypeError: Cannot read properties of null (reading 'removeChild')

### ISSUE THREAD

**Issue by muchukaingu** [Flutterwave/Flutterwave-Angular-v3#16]
core.mjs:6485 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of null (reading 'removeChild')
TypeError: Cannot read properties of null (reading 'removeChild')
    at HTMLDivElement.Element.remove (v3.js:1:699)
    at OverlayRef.dispose (overlay.mjs:618:67)
    at MatTooltip.ngOnDestroy (tooltip.mjs:257:30)
    at executeOnDestroys (core.mjs:7357:1)
    at cleanUpView (core.mjs:7260:1)
    at destroyViewTree (core.mjs:7093:1)
    at destroyLView (core.mjs:7238:1)
    at RootViewRef.destroy (core.mjs:21238:1)
    at ComponentRef.destroy (core.mjs:21648:1)
    at RouterOutlet.deactivate (router.mjs:2503:28)
    at resolvePromise (zone.js:1213:1)
    at resolvePromise (zone.js:1167:1)
    at zone.js:1279:1
    at ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25505:1)
    at ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:582:1)
    at ZoneTask.invokeTask [as invoke] (zone.js:491:1)
    at invokeTask (zone.js:1600:1)

**Comment by toybz** [comment]
Hello @muchukaingu 
Please share more details about this issue to enable us investigate.

**Comment by toybz** [comment]
Issue has been resolved on skype channel with merchant.

**Comment by whizyrel** [comment]
@toybz Kindly share the fix for this
